<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ATDEV283L1" failures="1" tests="5" name="qa.ybl.testcases.TestLogin" time="13.880" errors="0" timestamp="2023-12-07T10:33:17 IST" skipped="0">
  <testcase classname="qa.ybl.testcases.TestLogin" name="Login_to_app" time="2.501"/>
  <testcase classname="qa.ybl.testcases.TestLogin" name="Login_to_app" time="2.496"/>
  <testcase classname="qa.ybl.testcases.TestLogin" name="Login_to_app" time="2.496"/>
  <testcase classname="qa.ybl.testcases.TestLogin" name="Login_to_app" time="2.496"/>
  <testcase classname="qa.ybl.testcases.TestLogin" name="Login_to_app" time="3.891">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at qa.ybl.testcases.TestLogin.Login_to_app(TestLogin.java:151)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:80)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:17)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- Login_to_app -->
</testsuite> <!-- qa.ybl.testcases.TestLogin -->
